DATA:
    ROOT: '/media/hd2/Engagement_data/StudentActionsDataset/VLMDataset/students_action_few_shots'
    TRAIN_FILE: '/media/hd2/Nady/Measuring_student_behavioural_engagement_framework/Zero_few_shots_setting/train_few_shot_16_cvpr.txt'
    VAL_FILE: '/media/hd2/Nady/Measuring_student_behavioural_engagement_framework/Zero_few_shots_setting/val_cvpr.txt'
    DATASET: studentActions
    NUM_FRAMES: 16
    NUM_CLASSES: 13
    LABEL_LIST: '/media/hd2/Nady/Measuring_student_behavioural_engagement_framework/Zero_few_shots_setting/labels_cvpr.csv'
MODEL:
    ARCH: ViT-B/16
TRAIN:
    BATCH_SIZE: 4 # BS 64
    ACCUMULATION_STEPS: 4
    EPOCHS: 50
    LR: 8.e-03
TRAINER:
  ViFi_CLIP:
    PROMPT_MODEL: True
    N_CTX_VISION: 10
    N_CTX_TEXT: 10
    PROMPT_DEPTH_VISION: 12
    PROMPT_DEPTH_TEXT: 12
SAVE_FREQ: 10